### ISSUE TITLE
Schema URLs for embedded objects show parent objects instead

### ISSUE THREAD

**Issue by konstin** [OParl/dev-website#18] opened 2016-09-20 10:16 UTC
E.g. https://schema.oparl.org/1.0/Consultation shows the schema for Paper

**Comment by eFrane** [comment] 2016-09-25 15:10
Due to embedded entities being embedded in the entity description of their respective parent
in OParl 1.0, this is intended behaviour.

**Comment by akuckartz** [comment] 2016-09-25 16:31
I think that this is surprising. What is the motivation for this behavior?

**Comment by eFrane** [comment] 2017-01-05 12:29
This is fixed now.

**Closed by eFrane** 2017-01-05 12:29 UTC
Labels: bug
